// ===== TECHNOLOGY TREE =====
const TECH=[
 {id:'t_pv2',b:'Energy',n:'Multi-junction solar cells',c:50,pre:[],d:'Three stacked semiconductor layers catch more of the spectrum: all panels 30% → 40% efficient.'},
 {id:'t_pv3',b:'Energy',n:'Concentrator solar arrays',c:180,pre:['t_pv2'],d:'Lenses focus sunlight on small high-grade cells: 47% efficient.'},
 {id:'t_cap',b:'Energy',n:'Supercapacitors',c:40,pre:[],d:'Charge stored on vast carbon surfaces: little energy, enormous power.'},
 {id:'t_ssb',b:'Energy',n:'Solid-state batteries',c:70,pre:[],d:'Solid electrolytes: twice the energy per kilogram of Li-ion.'},
 {id:'t_fly',b:'Energy',n:'Composite flywheels',c:60,pre:['t_cf'],d:'Carbon rotors spinning in vacuum: low energy density, huge power, no wear.'},
 {id:'t_fis',b:'Energy',n:'Space fission reactors',c:100,pre:[],d:'Steady power anywhere, even in shadow or far from the Sun.'},
 {id:'t_fis2',b:'Energy',n:'Brayton-cycle reactors',c:300,pre:['t_fis','t_hpr'],d:'Megawatt reactors with gas turbines.'},
 {id:'t_mcf',b:'Energy',n:'Magnetic-confinement fusion',c:1200,pre:['t_fis2','t_sc'],d:'Steady fusion reactors and the magnetic fusion drive: heavy and dependable.'},
 {id:'t_icf',b:'Energy',n:'Inertial-confinement fusion',c:1200,pre:['t_fis2','t_laser'],d:'Pellet fusion: lighter reactors and the high-thrust pulse drive, but harder on hardware.'},
 {id:'t_hpr',b:'Thermal',n:'High-temperature heat pipes',c:60,pre:[],d:'Radiators at 1,200 K reject ~250× more heat per m² than room-temperature panels (it scales with T⁴).'},
 {id:'t_ldr',b:'Thermal',n:'Liquid-droplet radiators',c:400,pre:['t_hpr'],d:'Molten-tin droplet sheets: enormous area for little mass.'},
 {id:'t_cf',b:'Materials',n:'Carbon composites',c:40,pre:[],d:'Lighter, stiffer frames; flywheel rotors; sail film.'},
 {id:'t_ti',b:'Materials',n:'High-strength alloys',c:70,pre:[],d:'Titanium-steel frames rated for 12 g.'},
 {id:'t_sc',b:'Materials',n:'High-temperature superconductors',c:200,pre:['t_cf'],d:'Zero-resistance wire: strong magnets for fusion, plasma engines, shields and accelerators.'},
 {id:'t_vas',b:'Propulsion',n:'Magnetoplasma propulsion',c:80,pre:[],d:'Radio-frequency plasma heating and magnetic nozzles.'},
 {id:'t_mpd',b:'Propulsion',n:'Magnetoplasmadynamic thrusters',c:250,pre:['t_vas','t_sc'],d:'Megawatt-class electric thrust.'},
 {id:'t_ntr',b:'Propulsion',n:'Nuclear thermal propulsion',c:120,pre:['t_fis'],d:'Reactor-heated hydrogen rockets.'},
 {id:'t_sail',b:'Propulsion',n:'Solar sails',c:60,pre:['t_cf'],d:'Ultra-thin carbon mirror film and deployable booms.'},
 {id:'t_eng2',b:'Propulsion',n:'Engine refinement Mk II',c:120,pre:[],d:'Upgrade engines you already own: +12% exhaust speed, −30% waste heat, −25% mass per watt.'},
 {id:'t_eng3',b:'Propulsion',n:'Engine refinement Mk III',c:450,pre:['t_eng2','t_sc'],d:'A second round of the same improvements.'},
 {id:'t_am',b:'Propulsion',n:'Antimatter production',c:3000,pre:['t_sc','t_fab3'],d:'Accelerators that make antiprotons, magnetic traps to hold them, and the photon rocket.'},
 {id:'t_beam',b:'Propulsion',n:'Beamed-core antimatter drive',c:5000,pre:['t_am'],d:'Magnetically steered pions: far more thrust per watt than light.'},
 {id:'t_eclss',b:'Life support',n:'Regenerative life support',c:80,pre:[],d:'Recycle water, make oxygen from water.'},
 {id:'t_bio',b:'Life support',n:'Bioregenerative greenhouse',c:250,pre:['t_eclss'],d:'Grow food and oxygen.'},
 {id:'t_pe',b:'Shielding',n:'Polyethylene shielding',c:40,pre:[],d:'Better protection per kilogram.'},
 {id:'t_ww',b:'Shielding',n:'Water-wall habitat',c:60,pre:[],d:'Your water supply doubles as shielding.'},
 {id:'t_mag',b:'Shielding',n:'Active magnetic shielding',c:500,pre:['t_sc'],d:'Deflect charged particles with superconducting coils.'},
 {id:'t_lab2',b:'Industry & science',n:'Onboard laboratory',c:40,pre:[],d:'6× faster research.'},
 {id:'t_lab3',b:'Industry & science',n:'Research station',c:400,pre:['t_lab2','t_fab2'],d:'30 research points per hour.'},
 {id:'t_fab2',b:'Industry & science',n:'Industrial fabrication',c:80,pre:[],d:'5 MW of manufacturing.'},
 {id:'t_robo',b:'Industry & science',n:'Autonomous robotics',c:60,pre:[],d:'Mining drones: they fly to an asteroid near you, dig, and bring the ore home (key 8).'},
 {id:'t_probe',b:'Industry & science',n:'Deep-space probes',c:100,pre:['t_lab2'],d:'Science probes you launch to other worlds; their data returns at the speed of light (key 8).'},
 {id:'t_hall',b:'Propulsion',n:'Hall-effect thrusters',c:30,pre:[],d:'The workhorse of satellite propulsion: more thrust per watt than gridded ion engines.'},
 {id:'t_arc',b:'Propulsion',n:'Arcjets',c:25,pre:[],d:'Electric arcs heat hydrogen: simple, sturdy, 12 km/s.'},
 {id:'t_solth',b:'Propulsion',n:'Solar thermal propulsion',c:60,pre:['t_cf'],d:'Concentrated sunlight heats hydrogen: 8 km/s with no reactor.'},
 {id:'t_esail',b:'Propulsion',n:'Electric sails',c:120,pre:['t_cf'],d:'Charged tethers ride the solar wind: thrust without propellant that fades only as 1/distance.'},
 {id:'t_gcnr',b:'Propulsion',n:'Gas-core nuclear rockets',c:300,pre:['t_ntr'],d:'Fissioning uranium gas heats hydrogen: 30 km/s with enormous thrust.'},
 {id:'t_dfd',b:'Propulsion',n:'Direct fusion drive',c:500,pre:['t_sc'],d:'A compact magnetic-mirror fusion reactor whose exhaust is the thrust.'},
 {id:'t_fab3',b:'Industry & science',n:'Orbital factory',c:600,pre:['t_fab2'],d:'500 MW of manufacturing.'},
 {id:'t_laser',b:'Weapons',n:'Pulsed lasers',c:50,pre:[],d:'The pulse laser.'},
 {id:'t_missile',b:'Weapons',n:'Guided missiles',c:40,pre:[],d:'Missile bay and missiles.'},
 {id:'t_rail',b:'Weapons',n:'Electromagnetic launchers',c:80,pre:['t_cap'],d:'The railgun (fed by supercapacitors).'},
 {id:'t_pbeam',b:'Weapons',n:'Particle accelerators',c:400,pre:['t_sc'],d:'The particle beam.'}];
const TK2={};TECH.forEach(t=>TK2[t.id]=t);const hasT=id=>!id||!!s.tech[id],techOK=t=>t.pre.every(hasT);
const WEP=[{id:'mlaser',n:'Mining laser',hold:true,range:1e6,d:'Continuous infrared laser that cracks and vaporises rock (about 2 MJ per kg). A collector catches 80% when you are within 10 km. Half its power becomes heat in the low-temperature loop.'},
 {id:'plaser',n:'Pulse laser',range:1e6,d:'10 MJ pulses (5 MJ reaches the target). Recharge time = 10 MJ ÷ your storage power.'},
 {id:'pbeam',n:'Particle beam',hold:true,range:3e5,d:'50 MW continuous beam, 40% reaches the target; 30 MW of heat. Range 300 km.'},
 {id:'rail',n:'Railgun',range:Infinity,d:'2 kg iron slug at 8 km/s per shot (64 MJ). Needs 128 MJ per shot: recharge time depends on your capacitors.'},
 {id:'missile',n:'Missile',range:Infinity,d:'Self-guided; homes on the selected target. 2×10⁷ J warhead plus impact energy.'}];
let WI=0,WT=null,fireHeld=false,PML=5e4,lastShot=0,lastShotT=-1e9,UID=0;const PSI=.4,PE=2e7;
s.parts.forEach(p=>p.uid=++UID);
